### ISSUE TITLE
Can't load the trianed master model

### ISSUE THREAD

**Issue by hnliu-git** [TurkuNLP/multilingual-register-labeling#1]
Hi! I am Haonan from Lingsoft. We are now working on the European Language Grid (ELG) project and we are interested in the multilingual register classification tool. We would like to develop a Flask API and dockerized it then push it to the ELG. 

However, after I downloaded the trained master model using the given link and use the following script to load it. I got this error. 
Script:
```
from tensorflow.keras.models import load_model
from keras_bert import get_custom_objects
print("Ldocker oading model..")
custom_objects = get_custom_objects()
model = load_model('model_xlmrL0.5_en+fi+fr+sv-common-8e-7-100.h5', custom_objects=custom_objects)
```

The error is
```
Traceback (most recent call last):
  File "/home/haonan/Projects/lingsoft_projects/multilingual-register-labeling-master/bert_predict.py", line 133, in <module>
    model = load_model('model_xlmrL0.5_en+fi+fr+sv-common-8e-7-100.h5', custom_objects=custom_objects)
  File "/home/haonan/anaconda3/envs/multilingual-register-labeling-master/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 143, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/haonan/anaconda3/envs/multilingual-register-labeling-master/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 159, in load_model_from_hdf5
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.
```

The versions of packages are
-  tensorflow==1.15.0
- keras-bert==0.88.0

Could you give me some comments on how to load the model correctly? Thank you in advance!

**Comment by sronnqvist** [comment]
Hi! That's very nice to hear that you are interested in this.
The trained model is a weights file, so you need to first build the model using the existing code and then load the weights, see: https://github.com/sronnqvist/transformers-classifier/blob/22fe6466bc719f596f5e4f2f2a8225386882b71f/train.py#L745

In the latest version of the code (linked), we support loading both from weights and model files. A trained model can be saved in either format, but please note that the latter requires the special `save_trained_model`/`load_trained_model`, normal keras load_model doesn't work.

-Samuel

**Comment by hnliu-git** [comment]
Hi, Samuel! Thank you for the reply. However, I still have trouble loading the model using the script. We only want to use the trained model for inference and we used the following script.
```
from transformers import AutoConfig, AutoTokenizer, TFAutoModel

def load_pretrained(name):
    config = AutoConfig.from_pretrained(name)
    config.return_dict = True
    tokenizer = AutoTokenizer.from_pretrained(name, config=config)
    model = TFAutoModel.from_pretrained(name, config=config)

    return model, tokenizer, config


def get_pretrained_model_main_layer(model):
    from transformers import TFXLMRobertaModel
    return model.roberta

from tensorflow.keras import Model
from tensorflow.keras.layers import Input, Dropout, Dense


def build_classifier(pretrained_model, num_labels, seq_len=512):
    # workaround for lack of support for saving pretrained models
    pretrained_model = get_pretrained_model_main_layer(pretrained_model)

    input_ids = Input(
        shape=(seq_len,), dtype='int32', name='input_ids')
    attention_mask = Input(
        shape=(seq_len,), dtype='int32', name='attention_mask')
    inputs = [input_ids, attention_mask]

    pretrained_outputs = pretrained_model(inputs)
    pooled_output = pretrained_outputs['last_hidden_state'][:, 0, :]  # CLS

    # TODO consider Dropout here
    output = Dense(num_labels, activation='softmax')(pooled_output)

    model = Model(
        inputs=inputs,
        outputs=[output]
    )

    return model


pretrained_model, tokenizer, model_config = load_pretrained('jplu/tf-xlm-roberta-large')
clf = build_classifier(pretrained_model, 8)
clf.load_weights('model_xlmrL0.5_en+fi+fr+sv-common-8e-7-100.h5')
```
The raised error is
```
Traceback (most recent call last):
  File "/home/haonan/Projects/lingsoft_projects/multilingual-register-labeling-master/bert_predict.py", line 199, in <module>
    clf.load_weights('model_xlmrL0.5_en+fi+fr+sv-common-8e-7-100.h5')
  File "/home/haonan/anaconda3/envs/multilingual-register-labeling-master/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2211, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/home/haonan/anaconda3/envs/multilingual-register-labeling-master/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 708, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/haonan/anaconda3/envs/multilingual-register-labeling-master/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/haonan/anaconda3/envs/multilingual-register-labeling-master/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3576, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype(x)))
  File "/home/haonan/anaconda3/envs/multilingual-register-labeling-master/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 858, in assign
    self._shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/haonan/anaconda3/envs/multilingual-register-labeling-master/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (1, 1024) and (514, 1024) are incompatible
```
Except for this issue, could you tell me where can I find the `label.txt` for this register classification task?

Thank you!

-Haonan
